### ISSUE TITLE
API Key is invalid

### ISSUE THREAD

**Issue by ChubaOraka** [smoldata/smol-maps#9]
When the app is built for the first time by running the make command and launched in a browser, the Mapzen key is not accepted.
![image](https://user-images.githubusercontent.com/17247707/33522571-ba1e478e-d7bd-11e7-92ae-efb78ddcf89c.png)

The Mapzen API key is accepted as valid only when the make command is run a second time.

**Comment by dphiffer** [comment]
Thanks, @ChubaOraka. I'm gonna see if I can replicate this one.

**Comment by dphiffer** [comment]
So weird, I downloaded a fresh copy of the code then did `make` and then `npm start`. Oddly it accepted my API key on the first try. I wonder if I'm doing something differently somehow?

**Comment by dphiffer** [comment]
Oh, I figured out what's happening, it's a Chrome-specific thing. I've been testing everything on Firefox.
